name: Deploy Package

env:
  PKG_ID: com.gametoolkit.localization

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
   # branches: [ upm ]
  #pull_request:
   # branches: [ upm ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Commit changes to upm branch
        run: git subtree split --prefix=Packages/$PKG_ID --branch upm

      - name: Create version tag
        run: |
          VERSION=$(python -c "import json;print json.loads(open('Packages/$PKG_ID/package.json', 'r').read())['version']")
          git tag $VERSION upm

      - name: Push version and upm branch
        run: git push origin upm --tags --force
